"""add file_versions table

Revision ID: 6ddf67f96acc
Revises: b49e0efeef7d
Create Date: 2025-09-21 13:10:02.883377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ddf67f96acc'
down_revision = 'b49e0efeef7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('commit_message', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['repository_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('repository_files', sa.Column('change_info', sa.JSON(), nullable=True))
    op.add_column('repository_files', sa.Column('storage_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_files', 'storage_path')
    op.drop_column('repository_files', 'change_info')
    op.drop_table('file_versions')
    # ### end Alembic commands ###