"""add merge_request_versions table

Revision ID: ca05db2c34a6
Revises: 6ddf67f96acc
Create Date: 2025-09-21 13:32:50.862883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca05db2c34a6'
down_revision = '6ddf67f96acc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merge_request_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merge_request_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ai_validation_status', sa.String(), nullable=True),
    sa.Column('ai_validation_score', sa.Float(), nullable=True),
    sa.Column('ai_validation_feedback', sa.Text(), nullable=True),
    sa.Column('ai_validation_concerns', sa.JSON(), nullable=True),
    sa.Column('ai_validation_suggestions', sa.JSON(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merge_request_id'], ['merge_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merge_request_versions')
    # ### end Alembic commands ###